import { AppProps } from "next/app";
import { CacheProvider, EmotionCache } from "@emotion/react";

import createEmotionCache from "../utility/createEmotionCache";
import "@assets/fonts/fonts.scss";
import Head from "next/head";

import { UiThemeProvider } from "providers/theme.provider";

const clientSideEmotionCache = createEmotionCache();

interface Props extends AppProps {
  emotionCache: EmotionCache;
}

function MyApp({
  Component,
  pageProps,
  emotionCache = clientSideEmotionCache,
}: Props) {
  return (
    <CacheProvider value={emotionCache}>
      <UiThemeProvider>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </UiThemeProvider>
    </CacheProvider>
  );
}

export default MyApp;
