import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({ data }) {
  const { Title: title } = data.data.attributes;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>{title}</h1>
      </main>
    </div>
  )
}

export async function getStaticProps(context) {
  const res = await fetch(`${process.env.BACK_URL}/api/home-page`)
  const data = await res.json()
  return {
    props: {
      data
    },
    revalidate: 60
  }
}
