import Head from 'next/head'
import Image from 'next/image'

import { DefaultLayout } from '../layouts/default-layout/default-layout';

import { homePageApi } from '../api/requests/home-page.api';

import styles from '../styles/Home.module.css'
import { headerApi } from '../api/requests/header.api';

export default function Home({ pageData, headerData }) {
  const title = pageData?.data?.attributes?.Title;
  return (
    <DefaultLayout /* headerData={headerData} */ title={title}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          {title && <h1>{title}</h1>}
        </main>
      </div>
    </DefaultLayout>
  )
}

export const getServerSideProps = async () => {

  const pageRes = homePageApi.getHomePage()
  const headerRes = headerApi.getHeader()

  const responses = await Promise.all([pageRes, headerRes])

  return {
    props: {
      pageData: responses[0],
      headerData: responses[1]
    }
  }
}
