import Head from 'next/head'

import { Stack, TextField, Button } from '@mui/material';
import { DefaultLayout } from '../layouts/default-layout/default-layout';

import { signInPageApi } from '../api/requests/sign-in-page.api';
import { headerApi } from '../api/requests/header.api';

import styles from '../styles/Home.module.css'
import { useState } from 'react';

export default function SignIn({ pageData, headerData }) {

    const [dataValid, setDataValid] = useState({
        email: null,
        password: null
    })

    const [loginData, setLoginData] = useState({
        email: null,
        password: null
    })

    const handleChange = (e) => {
        const { name, value } = e.target;
        setLoginData(prevValues => ({
            ...prevValues,
            [name]: value
        }));
    }

    const handleSubmit = async (e) => {
        e.preventDefault();
        const res = await fetch(`http://localhost:1337/api/auth/local/`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                identifier: loginData.email,
                password: loginData.password
            })
        });
        const data = await res.json();
        alert(`Hello, ${data.user.username}`)
        return data;
    }

    const title = pageData?.attributes?.title;
    return (
        <DefaultLayout headerData={headerData} title={title}>
            <div>
                <Head>
                    <title>{title}</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    {title && <h1>{title}</h1>}
                    <form onSubmit={handleSubmit}>
                        <Stack spacing={2} sx={{ minWidth: 320 }}>
                            <TextField name="email" label="Email" variant="standard" type="email" onChange={handleChange} />
                            <TextField name="password" label="Password" variant="standard" type="password" onChange={handleChange} />
                            <Button variant="contained" type="submit">Log in</Button>
                        </Stack>
                    </form>
                </main>
            </div>
        </DefaultLayout>
    )
}

export const getStaticProps = async () => {

    const pageRes = signInPageApi.getSignInPage()
    const headerRes = headerApi.getHeader()

    const responses = await Promise.all([pageRes, headerRes])

    return {
        props: {
            pageData: responses[0],
            headerData: responses[1]
        },
        revalidate: 1
    }
}
